./run.sh mlp_0
./run.sh mlp_1
./run.sh mlp_2
./run.sh mlp_3
./run.sh transformer_0
./run.sh transformer_1
./run.sh transformer_2
./run.sh transformer_3
./run.sh mlp_features_0
./run.sh mlp_features_1
./run.sh mlp_features_2
./run.sh mlp_features_3
./run.sh mlp_features_4
./run.sh mlp_features_5
./run.sh mlp_features_6
./run.sh mlp_features_7
./run.sh mlp_features_8
./run.sh mlp_features_9
./run.sh mlp_features_10
./run.sh mlp_features_11
./run.sh mlp_features_12
./run.sh mlp_features_13
./run.sh mlp_features_14
./run.sh mlp_features_15
./run.sh mlp_features_16
./run.sh mlp_features_17
./run.sh mlp_features_18
./run.sh mlp_features_19
./run.sh mlp_features_20
./run.sh mlp_features_21
./run.sh mlp_features_22
./run.sh mlp_features_23
./run.sh transformer_features_0
./run.sh transformer_features_1
./run.sh transformer_features_2
./run.sh transformer_features_3
./run.sh transformer_features_4
./run.sh transformer_features_5
./run.sh transformer_features_6
./run.sh transformer_features_7
./run.sh transformer_features_8
./run.sh transformer_features_9
./run.sh transformer_features_10
./run.sh transformer_features_11
./run.sh transformer_features_12
./run.sh transformer_features_13
./run.sh transformer_features_14
./run.sh transformer_features_15
./run.sh transformer_features_16
./run.sh transformer_features_17
./run.sh transformer_features_18
./run.sh transformer_features_19
./run.sh transformer_features_20
./run.sh transformer_features_21
./run.sh transformer_features_22
./run.sh transformer_features_23